### ISSUE TITLE
Variablen nach Update doppelt

### ISSUE THREAD

**Issue by cfis72** [Brovning/e3dc#5]
Hallo,

vielen Dank für das Update.
Nach dem Update sind bei mir einige Variablen doppelt vorhanden:
Ordner DC_String
Autarkie
Eigenverbrauch
Var. im Ordner EMC-Status

![image](https://user-images.githubusercontent.com/57300783/69800424-84af2b00-11d5-11ea-98ca-c155699bf64a.png)

**Comment by Brovning** [comment]
Hallo,
von den doppelten Variablen sollte nur eine aktualisiert werden. Bitte die Anderen manuell löschen oder die Modul-Instanz neu erstellen.
Beim DC-String Ordner muss du leider ausprobieren, welcher gelöscht werden kann. Im Zweifelsfall beide löschen oder eben die Modul-Instanz neu erstellen.

Mein Modul wurde auch mit diesen Änderungen für den Stable-Kanal abgelehnt, so dass ich auch für das nächste Update leider wieder größere Umbauten vornehmen muss...
Sorry!

Gruß

Jürgen
